/*
 * generated by Xtext 2.16.0
 */
package org.xtext.example.mydsl


/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
class WPDslStandaloneSetup extends WPDslStandaloneSetupGenerated {

	def static void doSetup() {
		new WPDslStandaloneSetup().createInjectorAndDoEMFRegistration()
	}
}
